# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZ3smkGpPlyZiok5PL0jcnMrdpQ2DuqS
"""

import streamlit as st
import pandas as pd
import joblib
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

st.set_page_config(page_title="ML Assignment-2", layout="wide")
st.title("📊 Machine Learning Classification Dashboard")

uploaded_file = st.file_uploader("Upload Test CSV File", type="csv")

model_map = {
    "Logistic Regression": "logistic",
    "Decision Tree": "decision_tree",
    "KNN": "knn",
    "Naive Bayes": "naive_bayes",
    "Random Forest": "random_forest",
    "XGBoost": "xgboost"
}

model_name = st.selectbox("Select Model", list(model_map.keys()))

if uploaded_file:
    data = pd.read_csv(uploaded_file)

    X = data.drop("default.payment.next.month", axis=1)
    y = data["default.payment.next.month"]

    model = joblib.load(f"models/saved_models/{model_map[model_name]}.pkl")
    y_pred = model.predict(X)

    st.subheader("📌 Classification Report")
    st.text(classification_report(y, y_pred))

    st.subheader("📌 Confusion Matrix")
    cm = confusion_matrix(y, y_pred)

    fig, ax = plt.subplots()
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax)
    st.pyplot(fig)